---
title: "A"
author: "Anıl İsmet AŞCI"
output:
 rmdformats::robobook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("https://raw.githubusercontent.com/aiasci/firms/master/graphs.R")
```


<div><a href="https://aiasci.github.io/firms/sectoral.html">Sectoral Reports </a> </div>

# Income Statment

## Exports

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_exp
```


## Costs

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_gr_gp
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_op
```


## FX

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_fxp
```


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_fxl
```


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_nop
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_nop_s
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_nop_us
```


## Extraordinary

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_nep
```


## EBIT

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_ebit
```

## Profit

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_p
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_tns
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_nnp
```


# Balance Sheet

## Cash

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_cta
```

## Inventories

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_ita
```

## Capital

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_capta
```

### Proportion of Tangible Goods

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_a_l
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_a_m
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_a_s
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_a_mm
```

### Proportion of Tangible Goods 2

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_a_l_1
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_a_m_1
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_a_s_1
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_a_mm_1
```


## Receivables

### Trade

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_strta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_stdta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_ltrta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_ltdta
```

### Other


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_sorta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_sodta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_lorta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_lotda
```

## Financial Debt


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_strfl
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_ltrfl
```

## Equity


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_equ
```

# Capability of paying debt


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_ebitda
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_ebitdad
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_cur
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
a_acid
```

