---
title: "F"
author: "Anıl İsmet AŞCI"
output:
 rmdformats::robobook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("https://raw.githubusercontent.com/aiasci/firms/master/graphs.R")
```



# Exports

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_exp
```


# Costs

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_gr_gp
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_op
```


# FX

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_fxp
```


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_fxl
```


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_nop
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_nop_s
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_nop_us
```


# Extraordinary

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_nep
```


# EBIT

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_ebit
```

# Profit

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_p
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_tns
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_nnp
```


# Cash

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_cta
```

# Inventories

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_ita
```

# Capital

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_capta
```

# Receivables

## Trade

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_strta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_stdta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_ltrta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_ltdta
```

## Other


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_sorta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_sodta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_lorta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_lotda
```

# Financial Debt


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_strfl
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_ltrfl
```

# Equity


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_equ
```

# Capability of paying debt


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_ebitda
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_ebitdad
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_cur
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
f_acid
```

