---
title: "G"
author: "Anıl İsmet AŞCI"
output:
 rmdformats::robobook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("https://raw.githubusercontent.com/aiasci/firms/master/graphs.R")
```



# Exports

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_exp
```


# Costs

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_gr_gp
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_op
```


# FX

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_fxp
```


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_fxl
```


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_nop
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_nop_s
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_nop_us
```


# Extraordinary

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_nep
```


# EBIT

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_ebit
```

# Profit

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_p
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_tns
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_nnp
```


# Cash

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_cta
```

# Inventories

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_ita
```

# Capital

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_capta
```

# Receivables

## Trade

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_strta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_stdta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_ltrta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_ltdta
```

## Other


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_sorta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_sodta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_lorta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_lotda
```

# Financial Debt


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_strfl
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_ltrfl
```

# Equity


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_equ
```

# Capability of paying debt


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_ebitda
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_ebitdad
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_cur
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
g_acid
```

