---
title: "Q"
author: "Anıl İsmet AŞCI"
output:
 rmdformats::robobook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("https://raw.githubusercontent.com/aiasci/firms/master/graphs.R")
```

<div><a href="https://aiasci.github.io/firms/sectoral.html" target="_blank">Sectoral Reports </a> </div>

# Exports

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_exp
```


# Costs

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_gr_gp
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_op
```


# FX

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_fxp
```


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_fxl
```


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_nop
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_nop_s
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_nop_us
```


# Extraordinary

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_nep
```


# EBIT

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_ebit
```

# Profit

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_p
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_tns
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_nnp
```


# Cash

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_cta
```

# Inventories

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_ita
```

# Capital

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_capta
```

# Receivables

## Trade

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_strta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_stdta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_ltrta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_ltdta
```

## Other


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_sorta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_sodta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_lorta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_lotda
```

# Financial Debt


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_strfl
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_ltrfl
```

# Equity


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_equ
```

# Capability of paying debt


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_ebitda
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_ebitdad
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_cur
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
q_acid
```

