---
title: "R"
author: "Anıl İsmet AŞCI"
output:
 rmdformats::robobook
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source("https://raw.githubusercontent.com/aiasci/firms/master/graphs.R")
```


<div><a href="https://aiasci.github.io/firms/sectoral.html">Sectoral Reports </a> </div>

# Income Statment

## Exports

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_exp
```


## Costs

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_gr_gp
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_op
```


## FX

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_fxp
```


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_fxl
```


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_nop
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_nop_s
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_nop_us
```


## Extraordinary

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_nep
```


## EBIT

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_ebit
```

## Profit

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_p
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_tns
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_nnp
```


# Balance Sheet

## Cash

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_cta
```

## Inventories

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_ita
```

## Capital

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_capta
```

### Proportion of Tangible Goods

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_r_l
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_r_m
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_r_s
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_r_mm
```

### Proportion of Tangible Goods 2

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_r_l_1
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_r_m_1
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_r_s_1
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
fig_r_mm_1
```


## Receivables

### Trade

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_strta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_stdta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_ltrta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_ltdta
```

### Other


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_sorta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_sodta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_lorta
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_lotda
```

## Financial Debt


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_strfl
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_ltrfl
```

## Equity


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_equ
```

# Capability of paying debt


```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_ebitda
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_ebitdad
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_cur
```

```{r warning=FALSE,error=FALSE,message=FALSE,echo=FALSE}
r_acid
```

